### ISSUE TITLE
How to size up the costmap size?

### ISSUE THREAD

**Issue by er1c-cartman** [IhabMohamed/log-MPPI_ros#1]
Hi. I want to size up the local cost map but when I increased the size, this error is occurring
and also I want to size up the resolution but also having an error
How can I adjust the size of local costmap and resolution?
Best regards

Traceback (most recent call last):
  File "/home/home/mppi_ws/src/log-MPPI_ros/mppi_control/src/mppi_control_node.py", line 504, in <module>
    MPPI_Controller_Node.run_mppi()
  File "/home/home/mppi_ws/src/log-MPPI_ros/mppi_control/src/mppi_control_node.py", line 402, in run_mppi
    u, normalizer, min_cost = self.jackal_controller.compute_control(
  File "/home/home/mppi_ws/src/log-MPPI_ros/mppi_control/scripts/mppi_control/mppi.py", line 501, in compute_control
    normalizer, min_cost = self.rollouts(state,
  File "/home/home/mppi_ws/src/log-MPPI_ros/mppi_control/scripts/mppi_control/mppi.py", line 391, in rollouts
    self.params_to_cuda(policy_params_adrs, kinematics_params_adrs,
  File "/home/home/mppi_ws/src/log-MPPI_ros/mppi_control/scripts/mppi_control/mppi.py", line 316, in params_to_cuda
    cuda.memcpy_dtod(costs_params_adrs[key], gpu_arr.ptr,
pycuda._driver.LogicError: cuMemcpyDtoD failed: invalid argument
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/timer.py", line 237, in run
    self._callback(TimerEvent(last_expected, last_real, current_expected, current_real, last_duration))
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_server.py", line 301, in publish_status_async
    self.publish_status()
  File "/opt/ros/noetic/lib/python3/dist-packages/actionlib/action_server.py", line 325, in publish_status
    self.status_pub.publish(status_array)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 882, in publish
    self.impl.publish(data)
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 1041, in publish
    raise ROSException("publish() to a closed topic")
rospy.exceptions.ROSException: publish() to a closed topic
[ WARN] [1706069643.564059268, 550.568000000]: Control loop missed its desired rate of 20.0000Hz... the loop actually took 0.0530 seconds
[mppi_control-2] process has died [pid 74905, exit code 1, cmd /home/home/mppi_ws/src/log-MPPI_ros/mppi_control/src/mppi_control_node.py odom:=ground_truth/odom goal:=move_base_simple/goal local_costmap:=move_base/local_costmap/costmap __name:=mppi_control __log:=/home/home/.ros/log/d755c504-ba6d-11ee-8cba-8786177b2fca/mppi_control-2.log].
log file: /home/home/.ros/log/d755c504-ba6d-11ee-8cba-8786177b2fca/mppi_control-2*.log

**Comment by er1c-cartman** [comment]
also it doesn't seems to follow the global path
i mean it is showing on rviz, but it doesn't seem mppi is following it
is there any way to let robot follow the global path? also is there some version that has a recovery mode?

best regards :)

**Comment by IhabMohamed** [comment]
Hi @er1c-cartman,

I apologize for the delayed response. To modify the costmap size or resolution, please update the values in the following files:

1. 'mppi_params_sim.yaml': [Link to file](https://github.com/IhabMohamed/log-MPPI_ros/blob/3378e231a63f020ccb5df50afe9013b8c664ad96/mppi_control/resources/mppi_params/mppi_params_sim.yaml#L33)

2. 'local_costmap_params.yaml': [Link to file](https://github.com/IhabMohamed/log-MPPI_ros/blob/main/mppi_control/resources/costmap_params/local_costmap_params.yaml#L1)

This should resolve the issue.

Regarding the waypoint navigation, our current controller does not strictly adhere to the waypoints provided by the global planner. I recommend checking out our latest work at [GP-MPPI](https://github.com/IhabMohamed/GP-MPPI) for an improved approach. Alternatively, you can refer to the Jackal Tutorials at [Jackal Navigation](https://www.clearpathrobotics.com/assets/guides/kinetic/jackal/navigation.html).

I hope this information is helpful.

Best regards!
